import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import GlobalLayout from "./globalLayout";

export const metadata = {
  title: "Frontend Sample",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  /*
    According to the figma file, the width of the screen is 400px, but here is 500px as a max width.
    This could and should be changed to fit according to the design which means 400px for the max screen width.
    But it will be left as 500px for the text.

    @TODO And it seems the font isnt working???
    
  */
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-[#efefef]">
        <div className="m-auto h-screen max-w-[500px] overflow-auto bg-white">
          <GlobalLayout>{children}</GlobalLayout>
          <div id="custom-drawer" />
          <div id="custom-modal" />
        </div>
      </body>
    </html>
  );
}
